In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import test

The initialization template is either None or invalid, the servers and jobs will be generated randomly


In [33]:
bt = test.get_some_tensor_states(2)

In [43]:
bt.size()

torch.Size([2, 12])

In [100]:
bt.gather(dim=0, index=test.torch.tensor(inx))

tensor([[  1.0000, 899.1851,   2.3370,   1.4948,   2.0342,   5.8480,   3.6813,
           1.7825,   4.1238,   3.2656,   3.2448,   0.0000]])

In [61]:
bt

tensor([[1.0000e+00, 8.8116e+02, 2.3370e+00, 1.4948e+00, 2.0342e+00, 5.8480e+00,
         3.6813e+00, 1.7825e+00, 4.1238e+00, 3.2656e+00, 3.2448e+00, 0.0000e+00],
        [1.0000e+00, 8.9919e+02, 2.3370e+00, 7.2770e-01, 2.0342e+00, 5.8480e+00,
         3.6813e+00, 1.7825e+00, 4.1238e+00, 3.2656e+00, 3.2448e+00, 0.0000e+00]])

In [102]:
bt.gather(dim=1, index=test.torch.tensor([[11],[11]]))

tensor([[0.],
        [0.]])

In [99]:
inx = [[0,1,0,0,0,0,0,0,0,0,0,1]]

In [94]:
len(inx[0])

12